### PR TITLE
Add details about serviceAutoStartProvider

### PR DESCRIPTION
**Pull request by samiraguiar**

### CODE REVIEW

**Comment by odinserj** [comment]
@samiraguiar, why did you close this PR?

**Comment by samiraguiar** [comment]
@odinserj I had missed that it was stated above `First, you’ll need a special class that implements the IProcessHostPreloadClient interface. It will be called automatically by Windows Process Activation service during its start-up and after each Application pool recycle.

**Comment by odinserj** [comment]
I think yes – sometimes people get confused with that string.

**Comment by samiraguiar** [comment]
@odinserj alright, reopening then.

**Comment by odinserj** [comment]
Merged! Thanks, @samiraguiar! Btw, I'm planning to replace the article with a NuGet package, I've started a new project for this – https://github.com/HangfireIO/Hangfire.IIS

**Pull request merged**
